# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Tone.destroy_all
Adjective.destroy_all
Flower.destroy_all
Bouquet.destroy_all

# ---------- USER ----------
daniela = User.create(username: "Daniela", password: "cats", email: "daniela.sandoval820@gmail.com")

mochi = User.create(username: "Mochi", password: "123", email: "mochi@gmail.com")

# ---------- TONES ----------
anger = Tone.create(name: "Anger")
fear = Tone.create(name: "Fear")
joy = Tone.create(name: "Joy")
sadness = Tone.create(name: "Sadness")
analytical = Tone.create(name: "Analytical")
confident = Tone.create(name: "Confident")
tentative = Tone.create(name: "Tentative")
# other = Tone.create(name: "Other")

# ---------- ADJECTIVES ----------
hatred = Adjective.create(name: "Hatred", tone_id: anger.id)
# anger_adj = Adjective.create(name: "Anger", tone_id: anger.id)
jealous = Adjective.create(name: "Jealous", tone_id: anger.id)
anxious = Adjective.create(name: "Anxious", tone_id: fear.id)
hopeless = Adjective.create(name: "Hopeless", tone_id: fear.id)
fear_adj = Adjective.create(name: "Fear", tone_id: fear.id)
love = Adjective.create(name: "Love", tone_id: joy.id)
joy_adj = Adjective.create(name: "Joy", tone_id: joy.id)
happiness = Adjective.create(name: "Happiness", tone_id: joy.id)
disappointed = Adjective.create(name: "Disappointed", tone_id: sadness.id)
sadness_adj = Adjective.create(name: "Sadness", tone_id: sadness.id)
yearn =  Adjective.create(name: "Yearn", tone_id: sadness.id)
thoughtful = Adjective.create(name: "Thoughtful", tone_id: analytical.id)
analytical_adj = Adjective.create(name: "Analytical", tone_id: analytical.id)
logical = Adjective.create(name: "Logical", tone_id: analytical.id)
confident_adj = Adjective.create(name: "Confident", tone_id: confident.id)
doubtful = Adjective.create(name: "Doubtful", tone_id: tentative.id)
tentative_adj = Adjective.create(name: "Tentative", tone_id: tentative.id)
powerful = Adjective.create(name: "Powerful", tone_id: fear.id)
rarity = Adjective.create(name: "Rarity", tone_id: joy.id)
faithfulness = Adjective.create(name: "Faithfulness", tone_id: confident.id)
gratitude = Adjective.create(name: "Gratitude", tone_id: joy.id)
cheerful = Adjective.create(name: "Cheerful", tone_id: joy.id)
strength = Adjective.create(name: "Strength", tone_id: confident.id)
spiritual = Adjective.create(name: "Spiritual", tone_id: joy.id)
wealth = Adjective.create(name: "Wealth", tone_id: joy.id)
beauty = Adjective.create(name: "Beauty", tone_id: joy.id)
self_confidence = Adjective.create(name: "Self Confidence", tone_id: confident.id)
fake = Adjective.create(name: "Fake", tone_id: anger.id)
glorious = Adjective.create(name: "Glorious", tone_id: joy.id)
whimsical = Adjective.create(name: "Whimsical", tone_id: joy.id)
wishful = Adjective.create(name: "Wishful", tone_id: tentative.id)
dread = Adjective.create(name: "Dread", tone_id: fear.id)
confused = Adjective.create(name: "Confused", tone_id: tentative.id)

# ---------- FLOWERS ----------
aconite = Flower.create(name: "Aconite", meaning: "I hate you so be careful", img_url: "https://cdn.billyoh.com/extra/wp-content/uploads/2016/06/wolfsbane.jpg", adjective_id: hatred.id)
apocynum = Flower.create(name: "Apocynum", meaning: "I doubt you", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/SpreadingDogbane.JPG/1200px-SpreadingDogbane.JPG", adjective_id: doubtful.id)
acacia = Flower.create(name: "Yellow Acacia", meaning: "Concealed love", img_url: "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/acacia-flowers-michaela-perryman.jpg", adjective_id: love.id)
althea = Flower.create(name: "Althea", meaning: "I'm consumed by my love", img_url: "https://cdn.webvanta.com/000000/51/74/sm/uploads/plant/1498941304-10985eaf2237dfc23/botanikfoto-462191-L.jpg", adjective_id: love.id)
ambrosia = Flower.create(name: "Ambrosia", meaning: "Your love is reciprocated", img_url: "https://roycroftdaylilies.com/files/image/Pink-Ambrosia-3.jpg", adjective_id: love.id)
ros_acacia = Flower.create(name: "Rose Acacia", meaning: "I hope we can be friends", img_url: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a00fac4f-18a6-4707-afa5-cfb1b064ae1b/da03qxe-90a2eed2-0e74-4c9e-ac71-5c7aceac0745.jpg/v1/fill/w_1024,h_768,q_75,strp/rose_acacia_by_calypso1977_da03qxe-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzY4IiwicGF0aCI6IlwvZlwvYTAwZmFjNGYtMThhNi00NzA3LWFmYTUtY2ZiMWIwNjRhZTFiXC9kYTAzcXhlLTkwYTJlZWQyLTBlNzQtNGM5ZS1hYzcxLTVjN2FjZWFjMDc0NS5qcGciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.siFAUeaWSctJkr91X6KzXHxL0-PuTUaBDDTueTDlF7U", adjective_id: tentative_adj.id)
achillea = Flower.create(name: "Achillea", meaning: "War and the power to overcome is mine", img_url: "https://img.crocdn.co.uk/images/products2/pl/20/00/00/78/pl2000007840.jpg?width=940&height=940", adjective_id: powerful.id)
achimenes = Flower.create(name: "Achimenes", meaning: "Such worth is rare", img_url: "https://farm1.staticflickr.com/805/26003002757_613fab2163_b.jpg", adjective_id: rarity.id)
adder = Flower.create(name: "Adder's Tongue", meaning: "Totally jealous of you", img_url: "https://pics.davesgarden.com/pics/2005/05/30/Todd_Boland/893349.jpg", adjective_id: jealous.id)
adonis = Flower.create(name: "Adonis", meaning: "Sad memories", img_url: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Adonis_annua_flor.jpg", adjective_id: sadness_adj.id)
african_violet = Flower.create(name: "African Violet", meaning: "I am extremely faithful", img_url: "https://www.treetop-nursery.com/wp-content/uploads/2018/10/African-Violet.jpg", adjective_id: faithfulness.id)
agrimony = Flower.create(name: "Agrimony", meaning: "I'm so grateful to you", img_url: "https://www.wildflower.co.uk/pub/media/catalog/product/cache/926507dc7f93631a094422215b778fe0/A/g/Agrimony_Wildflower_Plant13300927174f479aad65d28.jpg", adjective_id: gratitude.id)
ajuga = Flower.create(name: "Ajuga", meaning: "Cheerful heart", img_url: "https://cdn10.bigcommerce.com/s-2drwt2az/products/18365/images/45856/ajugablackscallophr2__56270.1493250414.1280.1280.jpg?c=2", adjective_id: cheerful.id)
allium = Flower.create(name: "Allium", meaning: "Having great strength", img_url: "https://images.homedepot-static.com/productImages/834c8e58-3778-4c97-be25-473372723f7f/svn/breck-s-flower-bulbs-72751-64_1000.jpg", adjective_id: strength.id)
allamanda = Flower.create(name: "Allamanda", meaning: "Spiritual chief", img_url: "http://plantsrescue.com/wp-content/uploads/2014/08/Allamanda-cathartica-flowers.jpg", adjective_id: spiritual.id)
almond_blossom = Flower.create(name: "Almond Blossom", meaning: "Lovers Charm
", img_url: "http://1.bp.blogspot.com/-J-G-uKP4NqM/UJvrG93SwQI/AAAAAAAACdM/3t3O0r1xti0/s1600/Almond-Blossom_Flower-.jpg", adjective_id: love.id)
alstroemeria = Flower.create(name: "Alstroemeria", meaning: "Wealth and fortune", img_url: "https://www.anniesannuals.com/signs/a/images/alstroemeria_tricolor_bloom_01.jpg", adjective_id: wealth.id)
alyssum = Flower.create(name: "Sweet Alyssum", meaning: "Worth beyond beauty", img_url: "http://www.markseton.co.uk/wp-content/uploads/2014/06/Alyssum-Purple.jpg", adjective_id: beauty.id)
amaryllis = Flower.create(name: "Amaryllis", meaning: "Self confident beautiful woman", img_url: "https://cdn.shopify.com/s/files/1/1081/9186/products/hippaestrum_-_Version_2_1024x1024.jpg?v=1514835304", adjective_id: self_confidence.id)
anchusa = Flower.create(name: "Anchusa", meaning: "You're fake", img_url: "https://www.anniesannuals.com/signs/a/images//anchusa_azurea_alkanet_02.jpg", adjective_id: fake.id)
baby_breathe = Flower.create(name: "Baby's Breath", meaning: "Ever lasting love", img_url: "https://d1y09goev9d4xi.cloudfront.net/wp-content/uploads/2017/08/babys-breath-million-star-bulks-wholesale-600x600.jpg", adjective_id: love.id)
begonia = Flower.create(name: "Begonia", meaning: "Please beware", img_url: "https://www.veseys.com/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/b/a/badaboomscarlet-badaboomscarlet-image-2052badaboomscarlet.jpg", adjective_id: anxious.id)
bird_para = Flower.create(name: "Bird Of Paradise", meaning: "Extremely faithful", img_url: "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/bird-of-paradise-flower-pierre-leclerc-photography.jpg", adjective_id: faithfulness.id)
black_thorn = Flower.create(name: "Blackthorn", meaning: "I have changed radically", img_url: "https://cdn.shopify.com/s/files/1/1186/5156/products/Blackthorn_86db6db5-5e9d-4f8e-91f4-006e0901def8_1024x1024.jpeg?v=1456914725", adjective_id: analytical_adj.id)
borage = Flower.create(name: "Borage", meaning: "You're rude...", img_url: "https://cdn11.bigcommerce.com/s-2ba96/images/stencil/1200x1800/products/717/1193/Borage_Borago_officinalis__57032.1452727262.jpg?c=2", adjective_id: hatred.id)
butterfly = Flower.create(name: "Butterful Weed", meaning: "If you love me, please let me go", img_url: "https://www.waysidegardens.com/images/xxl/49296.jpg", adjective_id: analytical_adj.id)
cypress = Flower.create(name: "Cypress", meaning: "Symbolizes hopelessness", img_url: "https://worldoffloweringplants.com/wp-content/uploads/2017/11/Ipomoea-quamoclit-Cypress-Vine4.jpg", adjective_id: hopeless.id)
cape_jas = Flower.create(name: "Cape Jasmine", meaning: "I am too happy", img_url: "https://cdn.webvanta.com/000000/51/74/slider_detail/uploads/plant/1502802185-0d964b19baa37b919/30631025_m-3.jpg", adjective_id: happiness.id)
camellia = Flower.create(name: "Pink Camellia", meaning: "Longing for you", img_url: "https://stmed.net/sites/default/files/camellia-wallpapers-27795-2349876.jpg", adjective_id: yearn.id)
clover = Flower.create(name: "White Clover", meaning: "Think of me", img_url: "https://images-na.ssl-images-amazon.com/images/I/91n1kjkOFCL._SL1500_.jpg", adjective_id: thoughtful.id)
red_camellia = Flower.create(name: "Red Camellia", meaning: "You're a flame in my heart", img_url: "https://www.aces.edu/wp-content/uploads/2019/02/shutterstock_611375129-2.jpg", adjective_id: love.id)
canna_lily = Flower.create(name: "Canna Lily", meaning: "Glorious. Simply Glorious", img_url: "https://www.highcountrygardens.com/media/catalog/product/c/a/canna-cannasol-canna-lily-orange-happy-cleo-cropped.jpg?width=700&height=700&canvas=700:700&quality=80&bg-color=255,255,255&fit=bounds", adjective_id: glorious.id)
carnation_pink = Flower.create(name: "Pink Carnation", meaning: "I'll never forget you", img_url: "https://www.thompson-morgan.com/product_images/100/zoom/z-DIAN-T16859-A_h.jpg", adjective_id: analytical_adj.id)
carnation_pur = Flower.create(name: "Purple Carnation", meaning: "You're magical", img_url: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Moondust-carnation.JPG", adjective_id: whimsical.id)
carnation_stripped = Flower.create(name: "Stripped Carnation", meaning: "Wish I could be with you", img_url: "https://www.premierseedsdirect.com/wp-content/uploads/2017/02/41580027-2.jpg", adjective_id: wishful.id)
carnation_yello = Flower.create(name: "Yellow Carnation", meaning: "I'm disappointed in you", img_url: "https://sc02.alicdn.com/kf/HTB1UB5xJVXXXXXGXVXXq6xXFXXX8/carnation-cut-flower-prices-Directly-Wholesale-Fresh.jpg_350x350.jpg", adjective_id: disappointed.id)
clarkia = Flower.create(name: "Clarkia", meaning: "Your witty conversation delights me", img_url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Caltha_palustris_%28navadna_kalu%C5%BEnica%29.jpg", adjective_id: cheerful.id)
daffodil = Flower.create(name: "Daffodil", meaning: "The sun shines when I'm with you", img_url: "https://images.homedepot-static.com/productImages/4e5bb2e3-fc4f-494c-8652-c2850918199e/svn/bloomsz-flower-bulbs-07589-64_1000.jpg", adjective_id: happiness.id)
dandelion = Flower.create(name: "Dandelion", meaning: "Wishes come true", img_url: "https://www.flowermeaning.com/flower-pics/Dandelion-Meaning.jpg", adjective_id: happiness.id)
eglantine_rose = Flower.create(name: "Sweet Briar Rose", meaning: "I wound to heal", img_url: "https://usercontent2.hubstatic.com/9044449_f520.jpg", adjective_id: sadness_adj.id)
enchanter_nightshade = Flower.create(name: "Enchanter's Nightshade", meaning: "Witchcraft 🔮", img_url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Enchanter%27s-nightshade_-_Circaea_lutetiana_%281%29_%2838527068055%29.jpg", adjective_id: whimsical.id)
gladioli = Flower.create(name: "Gladioli", meaning: "I'm a gladiator's flower", img_url: "https://d6p0gevo8s9lm.cloudfront.net/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/l/gladiolus-flower-bulbs.jpg", adjective_id: strength.id)
grass = Flower.create(name: "Grass", meaning: "Submit to me", img_url: "https://vignette.wikia.nocookie.net/planttycoon/images/9/9d/GRASS.JPG/revision/latest?cb=20160417142616", adjective_id: analytical_adj.id)
hellebore = Flower.create(name: "Hellebore", meaning: "A beautiful year ahead", img_url: "http://cdn.territorialseed.com/images/uploads/23621_10165_large.jpg", adjective_id: wishful.id)
hyacinth = Flower.create(name: "Purple Hyacinth", meaning: "Please forgive me", img_url: "https://www.hollandbulbfarms.com/Shared/Images/Product/Blue-Star-Hyacinth/84119.jpg", adjective_id: sadness_adj.id)
fish_gera = Flower.create(name: "Fish Geranim", meaning: "Disappointed expectation", img_url: "https://garden.org/pics/2014-02-27/Paul2032/47c258.jpg", adjective_id: disappointed.id)
hyacinth = Flower.create(name: "Yellow Hyacinth", meaning: "Symbolizes jealousy", img_url: "https://cdn.shopify.com/s/files/1/1902/7917/products/Hyacinth-Yellow-Queen_grande.jpg?v=1529958160", adjective_id: jealous.id)
hepatica = Flower.create(name: "Hepatica", meaning: "Symbolizes confidence", img_url: "https://cdn11.bigcommerce.com/s-z6b2k4z/products/310/images/4590/HEPATICA__94751.1515991407.1000.1200.jpg?c=2", adjective_id: confident_adj.id)
iris = Flower.create(name: "Iris", meaning: "I promise you my love", img_url: "https://www.americanmeadows.com/media/catalog/product/i/r/iris-hollandica-dutch-iris-purple-sapphire-beauty.jpg?width=700&height=700&canvas=700:700&quality=80&bg-color=255,255,255&fit=bounds", adjective_id: love.id)
king_cup = Flower.create(name: "Kingcup", meaning: "I wish I were rich", img_url: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Caltha_palustris_%28navadna_kalu%C5%BEnica%29.jpg", adjective_id: wealth.id)
lantana = Flower.create(name: "Lantana", meaning: "I am unyielding", img_url: "https://www.provenwinners.com/sites/provenwinners.com/files/imagecache/low-resolution/ifa_upload/lantana_luscious_royale_cosmo_tag_0.jpg", adjective_id: analytical_adj.id)
lilac = Flower.create(name: "Purple Lilca", meaning: "My first love", img_url: "https://cdn.pixabay.com/photo/2016/04/17/20/23/lilac-flower-1335490_960_720.jpg", adjective_id: love.id)
lily = Flower.create(name: "White Lily", meaning: "You are sweet and pure", img_url: "https://www.brambleberry.com/dw/image/v2/BCPL_PRD/on/demandware.static/-/Sites-brambleberry-master-catalog/default/dw568b160a/images/large/ingredients/fragrance-oils/main/WhiteLilyandAloe_FO251_Main.jpg?sw=1000&sh=1000&sm=fit", adjective_id: glorious.id)
tiger_lily = Flower.create(name: "Tiger Lily", meaning: "Stay wealthy and employed", img_url: "https://cdn.webvanta.com/000000/51/74/slider_detail/uploads/plant_family/1427309241-ab6d78c9bbff0acbd/57197.jpg", adjective_id: wealth.id)
lil_valley = Flower.create(name: "Lily Of The Valley", meaning: "You've made my life complete", img_url: "https://www.gardendesign.com/pictures/images/900x705Max/dream-team-s-portland-garden_6/lily-of-the-valley-fragrant-white-flower-pixabay_12700.jpg", adjective_id: joy_adj.id)
love_in_mist = Flower.create(name: "Love In A Mist", meaning: "You puzzle me", img_url: "https://www.edenbrothers.com/store/media/Seeds-Flowers/SFLOV112-1.jpg", adjective_id: confused.id)
lotus = Flower.create(name: "Lotus", meaning: "Enlightenment", img_url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Sacred_lotus_Nelumbo_nucifera.jpg", adjective_id: spiritual.id)
love_lies = Flower.create(name: "Love Lies Bleeding", meaning: "Hopelessness", img_url: "https://cdn10.bigcommerce.com/s-2drwt2az/products/16643/images/52265/3836_-_amaranthus_caudatus_%2528zieramaranth%2529__10805.1493261086.1280.1280.jpg?c=2", adjective_id: hopeless.id)
marigold = Flower.create(name: "Marigold", meaning: "Symbolizes jealousy and cruelty", img_url: "https://www.gardendesign.com/pictures/images/900x705Max/dream-team-s-portland-garden_6/marigold-flowers-orange-pixabay_12708.jpg", adjective_id: jealous.id)
mandrake = Flower.create(name: "Mandrake", meaning: "Ovecome your fear", img_url: "https://live.staticflickr.com/8236/8355929958_806f3ddd1f_b.jpg", adjective_id: fear_adj.id)
meadow_saffron = Flower.create(name: "Meadow Saffron", meaning: "My best days have passed", img_url: "https://cdn.webvanta.com/000000/51/74/slider_detail/uploads/plant/1506174184-c9e62c007e92a051c/DP7791%20Colchicum%20autumnale%20Nancy%20Lindsay.jpg", adjective_id: disappointed.id)
milkeweed = Flower.create(name: "Milkweed", meaning: "There's hope in misery", img_url: "http://b50ym1n8ryw31pmkr4671ui1c64-wpengine.netdna-ssl.com/wp-content/blogs.dir/11/files/2015/02/Common-Milkweed.jpg", adjective_id: tentative_adj.id)
monarda = Flower.create(name: "Monarda", meaning: "Your actions are unbearable", img_url: "https://www.johnnyseeds.com/dw/image/v2/BBBW_PRD/on/demandware.static/-/Sites-jss-master/default/dw413efb25/images/products/herbs/00827_02_wildbergamot.jpg?sw=1120", adjective_id: hatred.id)
moonflower = Flower.create(name: "Moonflower", meaning: "I only dream of love", img_url: "https://www.oscseeds.com/wp-content/uploads/2018/12/moonflower.jpg", adjective_id: love.id)
morning = Flower.create(name: "Morning Glory", meaning: "It's a new day", img_url: "https://www.almanac.com/sites/default/files/styles/primary_image_in_article/public/image_nodes/magenta-morning-glory.jpg?itok=f4TTNG5W", adjective_id: cheerful.id)
narcissus = Flower.create(name: "Narcissus", meaning: "You are selfish", img_url: "https://www.whiteflowerfarm.com/mas_assets/cache/image/5/4/8/e/21646.Jpg", adjective_id: hatred.id)
orchid = Flower.create(name: "Orchid", meaning: "You flatter me", img_url: "https://www.gildshire.com/wp-content/uploads/2019/04/orchid-4068853_1920.jpg", adjective_id: beauty.id)
pansy = Flower.create(name: "Pansy", meaning: "Think of me when I'm gone", img_url: "http://blog.dallasarboretum.org/wp-content/uploads/2018/01/2-tone-pansy.jpg", adjective_id: thoughtful.id)
peony = Flower.create(name: "Peony", meaning: "Have a happy life", img_url: "https://www.americanmeadows.com/media/catalog/product/p/e/peonies-pink-shutterstock-463922750-cropped_1.jpg?width=700&height=700&canvas=700:700&quality=80&bg-color=255,255,255&fit=bounds", adjective_id: happiness.id)
plum = Flower.create(name: "Plum Blossom", meaning: "Keep your prommise", img_url: "https://hokkaido-sightseeing.com/en/wp-content/uploads/2017/05/%E8%9F%B7%EF%BD%B3%E8%9F%AF%EF%BD%A1%E8%AD%B4%E3%83%BBDSC_5337.jpg", adjective_id: thoughtful.id)
poinsetta = Flower.create(name: "Poinsettia", meaning: "Be of good cheer", img_url: "http://static1.squarespace.com/static/54fbb611e4b0d7c1e151d22a/553d6c79e4b0bd2add1ae0a0/5a27337e085229553a2313f2/1543628399806/Photo+Nov+26%2C+1+58+45+PM.jpg?format=1500w", adjective_id: cheerful.id)
poppy = Flower.create(name: "Poppy", meaning: "Rememberance", img_url: "https://i.pinimg.com/originals/7f/7b/62/7f7b62a06ac86f36924fd6fccd32ad38.jpg", adjective_id: thoughtful.id)
ranunculus = Flower.create(name: "Ranunculus", meaning: "I am dazzled by your charm", img_url: "https://images.homedepot-static.com/productImages/0d73fbbf-d0c8-4313-87f0-559c42926473/svn/van-zyverden-flower-bulbs-21558-64_1000.jpg", adjective_id: joy_adj.id)
rhododendron = Flower.create(name: "Rhododendron", meaning: "Careful, I'm dangerous", img_url: "https://q7i2y6d5.stackpathcdn.com/wp-content/uploads/2011/03/Rhododendron.jpg", adjective_id: dread.id)
rose = Flower.create(name: "Red Rose", meaning: "I love you", img_url: "https://i.pinimg.com/originals/8a/1a/8d/8a1a8d5111189b144dd3591841f84409.jpg", adjective_id: love.id)
blk_rose = Flower.create(name: "Black Rose", meaning: "Farewell...", img_url: "http://2il.org/wp-content/uploads/2014/01/natural-black-rose-turkey-village-Halfeti.jpg", adjective_id: dread.id)
blue_rose = Flower.create(name: "Blue Rose", meaning: "You're a mystery", img_url: "https://i0.wp.com/sunflowerfloraldesigns.com/janice/wp-content/uploads/2018/01/BlueRoses.jpg?fit=720%2C810", adjective_id: whimsical.id)
pink_rose = Flower.create(name: "Gratitude", meaning: "I'm so grateful", img_url: "https://upload.wikimedia.org/wikipedia/commons/7/77/Pink_rose_.JPG", adjective_id: gratitude.id)
green_rose = Flower.create(name: "Green Rose", meaning: "I'm from Mars 👽", img_url: "https://i.pinimg.com/originals/4a/9d/3c/4a9d3c1512d51d7aa27bc76b9b8cebf2.jpg", adjective_id: whimsical.id)
yell_rose = Flower.create(name: "Yellow Rose", meaning: "New beginnings", img_url: "https://images.homedepot-static.com/productImages/bfacbd4e-7d2b-4e99-b4f3-360ec141f28e/svn/globalrose-flower-bouquets-100-yellow-roses-md-64_1000.jpg", adjective_id: thoughtful.id)
scabious = Flower.create(name: "Scabious", meaning: "I have lost everything", img_url: "https://cdn.shopify.com/s/files/1/1186/5156/products/Scabious_1024x1024.jpeg?v=1456914875", adjective_id: dread.id)
sunflower = Flower.create(name: "Sunflower", meaning: "I hope your wishes com true", img_url: "https://media.phillyvoice.com/media/images/sunflower_090819.2e16d0ba.fill-735x490.jpg", adjective_id: wishful.id)
sweet_pea = Flower.create(name: "Sweet Pea", meaning: "Remember me", img_url: "https://q7i2y6d5.stackpathcdn.com/wp-content/uploads/2013/02/sweet-peas.jpg", adjective_id: thoughtful.id)
tansy = Flower.create(name: "Tansy", meaning: "I declare war!", img_url: "http://www.yourfragrantgarden.com/uploads/5/4/4/1/54415515/tansy-1_orig.jpg", adjective_id: hatred.id)
trumpet_flower = Flower.create(name: "Trumpet Flower", meaning: "Thoughts of those departed", img_url: "https://cdn.gardenista.com/wp-content/uploads/2018/02/trumpet-vine-tanaka-flickr-1466x2199.jpg", adjective_id: thoughtful.id)
tulip = Flower.create(name: "Red Tulip", meaning: "Declaration of love", img_url: "https://images.homedepot-static.com/productImages/f8fb8acc-434c-4524-b56a-355b1d9bcc32/svn/garden-state-bulb-flower-bulbs-hof18-08-64_1000.jpg", adjective_id: love.id)
yell_tuli = Flower.create(name: "Yellow Tulip", meaning: "There's sunshine in your smile", img_url: "https://www.auntyflo.com/sites/default/files/flowerpictures/yellow-tulip-meaning-flowers.jpg", adjective_id: cheerful.id)
venus_car = Flower.create(name: "Venus's Car", meaning: "Fly With Me", img_url: "https://live.staticflickr.com/8748/16627048243_13e043c4a9_b.jpg", adjective_id: whimsical.id)
verbena = Flower.create(name: "Verbena", meaning: "I pray for you", img_url: "https://www.waysidegardens.com/images/xxl/30719.jpg", adjective_id: spiritual.id)
orange_lily = Flower.create(name: "Orange Lily", meaning: "Symbolizes hatred and disdain", img_url: "https://images.homedepot-static.com/productImages/8189a726-4da1-48c9-b016-8efb7f7f403a/svn/breck-s-flower-bulbs-60961-64_1000.jpg", adjective_id: hatred.id)
red_columbine = Flower.create(name: "Red Columbine", meaning: "Anxious Resolve", img_url: "https://live.staticflickr.com/5345/7393071288_3c1ee38ab3_b.jpg", adjective_id: anxious.id)
white_car = Flower.create(name: "White Carnation", meaning: "Sweet and lovely", img_url: "https://cdn.shopify.com/s/files/1/1766/2959/products/Grenadin_White_2_2048x.jpg?v=1535078702", adjective_id: love.id)
zinnia = Flower.create(name: "Mixed Zinnia", meaning: "Thinking of an absent friend", img_url: "https://parkseed.com/images/xxl/52099-pk-p1.jpg", adjective_id: thoughtful.id)
violet = Flower.create(name: "Violet", meaning: "Watchful and faithful, always", img_url: "https://www.goodfreephotos.com/albums/plants/violet-flower.jpg", adjective_id: faithfulness.id)
viscaria = Flower.create(name: "Viscaria", meaning: "Will you dance with me", img_url: "https://www.swallowtailgardenseeds.com/flowers/viscarias/viscaria-oculata-mix.jpeg", adjective_id: love.id)
wisteria = Flower.create(name: "Wisteria", meaning: "You are always welcomed", img_url: "https://images.unsplash.com/photo-1494486205133-727224a9f727?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80", adjective_id: joy_adj.id)
xeranthemum = Flower.create(name: "Xeranthemum ", meaning: "Cheerful in the face of adversity", img_url: "https://images.bonanzastatic.com/afu/images/32ad/0a8a/a174_4232816366/Heirloom_900_Seeds_Xeranthemum_Lumina_Double_Immortelle_Mix_Everlasting_Flower-01.jpg", adjective_id: cheerful.id)
zephyranthes = Flower.create(name: "Zephyranthes", meaning: "Fond caresses", img_url: "https://cdn.shopify.com/s/files/1/1419/7120/products/Zephyranthes_Robusta.SHUT_1024x.jpg?v=1551749436", adjective_id: love.id)

# ---------- BOUQUET ----------
# dan_bouq = Bouquet.create(name: "My first test", user_id: daniela.id)
# dan_bouq_two = Bouquet.create(name: "My second test", user_id: daniela.id)
# mochi = Bouquet.create(name: "My third test", user_id: mochi.id)
# ---------- BOUQUET FLOWERS ----------

# --------- FAVORITES ----------

puts "YOUR SEEDS HAVE BEEN PLANTED 🌱"
